multirestaurante/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.views.static import serve
from django.urls import include, path
from multirestaurante.settings import STATIC_ROOT, MEDIA_ROOT
from seguridad.views import auditoria
from sitio.views import *
from seguridad.index import *
from sitio.perfil import *
from seguridad.clave import *
from sitio.registro import *
from sitio.locale import *
from sitio.local import *
from sitio.faq import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',sitio,name='sitio'),
    path('panel/', index,  name='index'),
    path('seguridad/',include('seguridad.urls')),
    path('restaurante/', include('restaurante.urls')),
    path('auditoria/', auditoria),
    path('perfil/', perfil),
    path('localesusuarios/', locales),
    path('locales/', local),
    path('faq/', faq),
    path('clave/', clave),
    path('registro/', registro),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})
]

admin.site.site_header = 'ADMINISTRACION MULTIRESTAURANTE'
WKHTMLTOPDF_CMD_OPTIONS = {'encoding': 'utf8', 'quiet': True}

seguridad/urls.py
from django.conf.urls import url
from seguridad.login import login_session,logout_user
from seguridad.recuperar_clave import recuperar
from seguridad.clave import clave
from seguridad.usuarios import *

urlpatterns = [
    url(r'^login/', login_session),
    url(r'^logout/', logout_user),
    url(r'^recuperar/', recuperar),
    url(r'^usuarios/$', usuarios),
    url(r'^clave/$', clave),
]

restaurante/models.py
from decimal import Decimal
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
OBLIGADO, NATURAL, ESPECIAL = 'OBLIGADO A LLEVAR CONTABILIDAD', 'CONTRIBUYENTE NATURAL', 'CONTRIBUYENTE ESPECIAL'

class Dias (models.Model):
    descripcion = models.CharField(max_length=400)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    class Meta:
        verbose_name = 'Dias'
        verbose_name_plural = 'Dias'
        ordering = ('descripcion',)


class Usuarios(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    documento = models.CharField(max_length=20, default='')
    celular = models.CharField(max_length=20, default='')
    telefono = models.CharField(max_length=20, default='')
    direccion = models.CharField(max_length=200, default='')
    ubicacion = models.CharField(max_length=100, blank=True, null=True)
    foto = models.ImageField(upload_to='usuarios/', blank=True, null=True)
    visitante =  models.BooleanField(default=False)

    def __str__(self):
        return "{} {} | {}".format(self.user.first_name, self.user.last_name, self.documento)

    def datos(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)

    class Meta:
        verbose_name = 'Propietario'
        verbose_name_plural = "Propietarios"
        ordering = ('documento',)


class Categoria (models.Model):
    descripcion = models.CharField(max_length=400)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ('descripcion',)

class Local(models.Model):
    propietario = models.ForeignKey(Usuarios, blank=True, null=True, verbose_name="Propietario", on_delete=models.PROTECT)
    documento = models.CharField(max_length=50, blank=True, default='', verbose_name='Ruc')
    razonsocial = models.CharField(max_length=200, blank=True, null=True, verbose_name='Razón Social')
    nombreComercial = models.CharField(max_length=200, blank=True, null=True, verbose_name='Nombre Comercial')
    fotouno = models.ImageField(upload_to='local/%Y/%m', null=True, blank=True, verbose_name='Logo Comercial')
    fotodos = models.ImageField(upload_to='local/%Y/%m', null=True, blank=True, verbose_name='Foto Local')
    direccion = models.CharField(max_length=500, blank=True, null=True, verbose_name='Dirección')
    telefono = models.CharField(max_length=500, blank=True, null=True, verbose_name='telefono')
    correo = models.EmailField(max_length=150, blank=True, null=True, verbose_name='Correo')
    categoria = models.ForeignKey(Categoria, blank=True, null=True, verbose_name="Categoria", on_delete=models.PROTECT)
    descripcion = models.CharField(max_length=2500, blank=True, null=True, verbose_name='Descripcion')
    visita = models.IntegerField(default=0, verbose_name='Visita')
    valortotal = models.FloatField(default=0, blank=True, null=True)
    oferta = models.BooleanField(default=False, verbose_name='Oferta')
    estado = models.BooleanField(default=True)
    delete = models.BooleanField(default=False)
    ubicacion = models.CharField(max_length=1000, blank=True, default='', verbose_name='Ubicacion')

    def __str__(self):
        return '{}, {}, {}'.format(self.documento, self.razonsocial, self.nombreComercial)

    class Meta:
        verbose_name = 'Empresa'
        verbose_name_plural = 'Empresas'
        ordering = ('documento',)

class iplocalvisita(models.Model):
    local = models.ForeignKey(Local, blank=True, null=True, verbose_name="Local", on_delete=models.PROTECT)
    ip = models.CharField(max_length=200, blank=True, null=True, verbose_name='Ip')


    def __str__(self):
        return '{}, {}'.format(self.ip, self.local.nombreComercial)

class calificacionlocal(models.Model):
    local = models.ForeignKey(Local, blank=True, null=True, verbose_name="Local", on_delete=models.PROTECT)
    calificacion = models.IntegerField(default=0, blank=True, null=True, verbose_name='Valor')
    votante = models.ForeignKey(Usuarios, blank=True, null=True, verbose_name="Votante", on_delete=models.PROTECT)


    def __str__(self):
        return '{}, {}'.format(self.calificacion, self.local.nombreComercial)



class Faq(models.Model):
    pregunta = models.CharField(max_length=1050, blank=True, default='', verbose_name='Pregunta')
    respuesta = models.CharField(max_length=1200, blank=True, null=True, verbose_name='Respuesta')
    estado = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.pregunta)

    class Meta:
        verbose_name = 'Faq'
        verbose_name_plural = 'Faq'
        ordering = ('pregunta',)

class HorarioLocal(models.Model):
    local = models.ForeignKey(Local, blank=True, null=True, verbose_name="Local", on_delete=models.PROTECT)
    dia = models.ForeignKey(Dias, blank=True, null=True, verbose_name="Dia", on_delete=models.PROTECT)
    horaInicio = models.TimeField(default=timezone.now,verbose_name='Hora de apertura')
    horaFin = models.TimeField(default=timezone.now, verbose_name='Hora de cierre')
    estado = models.BooleanField(default=True)
    delete= models.BooleanField(default=False)

    def __str__(self):
        return "{}, {}: {} - {}".format(self.local.nombreComercial, self.dia, self.horaInicio, self.horaFin)


    class Meta:
        verbose_name = "Horario de Atención"
        verbose_name_plural = "Horarios de Atención"
        ordering = ('local',)


class Platos(models.Model):
    local=models.ForeignKey(Local, blank=True, null=True, verbose_name="Restaurante", on_delete=models.PROTECT)
    nombre = models.CharField(max_length=200, default='')
    descripcion = models.CharField(max_length=200, default='')
    descuento = models.IntegerField( default=0)
    precio = models.DecimalField(max_digits=11, decimal_places=2, default=Decimal('0.00'))
    preciooferta = models.DecimalField(max_digits=11, decimal_places=2, default=Decimal('0.00'))
    foto = models.ImageField(upload_to='local/%Y/%m', null=True, blank=True, verbose_name='Foto')
    oferta = models.BooleanField(default=True, verbose_name='Oferta')
    estado = models.BooleanField(default=True, verbose_name='Estado')
    delete = models.BooleanField(default=False)
    def __str__(self):
        return "{} {} {}".format(self.nombre, self.descripcion, self.precio)


    class Meta:
        verbose_name = 'Platos'
        verbose_name_plural = "Platos"
        ordering = ('nombre',)

seguridad/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.template.defaulttags import now

class Modulo(models.Model):
    url = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    icono = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=100)
    activo = models.BooleanField(default=True)
    orden = models.IntegerField(default=0)

    def __str__(self):
        return '{} ({})'.format(self.nombre, self.url)

    class Meta:
        verbose_name = 'Módulo'
        verbose_name_plural = 'Módulos'
        ordering = ['orden']

class ModuloGrupo(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=200, blank=True)
    icono = models.CharField(max_length=100)
    modulos = models.ManyToManyField(Modulo)
    grupos = models.ManyToManyField(Group)
    prioridad = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return '{} {}'.format(self.nombre, self.prioridad)

    class Meta:
        verbose_name = 'Grupo de Módulos'
        verbose_name_plural = 'Grupos de Módulos'
        ordering = ('prioridad', 'nombre')

    def modulos_activos(self):
        return self.modulos.filter(activo=True).order_by('nombre')

class AudiUsuarioTabla(models.Model):
    TIPOS_ACCIONES = (
        ('A', 'A'),   # Adicion
        ('M', 'M'),   # Modificacion
        ('E', 'E')    # Eliminacion
    )
    usuario = models.ForeignKey(User,on_delete=models.PROTECT, verbose_name='Usuario')
    tabla = models.CharField(max_length=100, verbose_name='Tabla')
    registroid = models.IntegerField(verbose_name='Registro Id')
    registroname = models.CharField(max_length=100,verbose_name='Registro Name')
    accion = models.CharField(choices=TIPOS_ACCIONES, max_length=10, verbose_name='Accion')
    fecha = models.DateField(verbose_name='Fecha')
    hora = models.TimeField(verbose_name='Hora')
    estacion = models.CharField(max_length=100, verbose_name='Estacion')

    def save(self, force_insert=False, force_update=False, using=None, **kwargs):
        self.registroname = self.registroname.upper()
        super(AudiUsuarioTabla, self).save(force_insert, force_update, using)


    def __str__(self):
        return "{} - {} [{}]".format(self.usuario.username, self.tabla, self.accion)

    class Meta:
        verbose_name = 'Auditoria Usuario '
        verbose_name_plural = 'Auditorias Usuarios'
        ordering = ('-fecha', 'hora')

class Correo(models.Model):
    correo = models.CharField(max_length=100)
    clave = models.CharField(max_length=100)

sitio/models.py
from django.db import models

# Create your models here.

sitio/views.py
from multirestaurante import settings
from django.shortcuts import render
from multirestaurante.funciones import *
import time
from django.utils.timezone import activate
from restaurante.models import Categoria, Local

activate(settings.TIME_ZONE)
from multirestaurante.config import *

def sitio(request):
    data = {
        'titulo': 'Multirestaurantes',
        'model': 'sitio',
        'saludo': 'Bienvenidos ' + NOMBRE_SISTEMA,
        'locales': Local.objects.filter(estado=True,delete=False).order_by('-valortotal')[:10],
        'categorias': Categoria.objects.filter(estado=True)
    }
    addUserData(request, data)
    return render(request,'sitio/sitio.html',data)

templates/sitio/clave.html
{% extends 'sitio/base.html' %}

{% block main %}

    <div class="page-header" style="background: url(/static/sitio/assets/img/banner1.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumb-wrapper">
                        <h2 class="page-title">Cambiar Clave</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-12 col-lg-4 page-sidebar">
                    <aside>
                        <div class="sidebar-box">
                            <div class="user">
                                <div class="usercontent">
                                    <h3>{{ request.user.first_name }} {{ request.user.last_name }}</h3>
                                    <h4>{{ request.user.email }}</h4>
                                </div>
                            </div>
                            <nav class="navdashboard">
                                <ul>
                                    <li>
                                        <a href="/perfil/">
                                            <i class="fas fa-user"></i>
                                            <span>Editar Información</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="active" href="/clave/">
                                            <i class="fas fa-user-lock"></i>
                                            <span>Cambiar Clave</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="/localesusuarios/">
                                            <i class="fas fa-credit-card"></i>
                                            <span>Ver Locales</span>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </aside>
                </div>
                <div class="col-lg-8 col-md-12 col-xs-12 page-content">
                    <div class="inner-box">
                        <form enctype="multipart/form-data" id="frmEntidad" method="POST"
                          action="/clave/" data-parsley-validate
                          class="form-horizontal form-label-left">{% csrf_token %}
                            <div class="row">

                                <input type="hidden" name="id" value="{{ request.user.pk }}">
                                <input type="hidden" name="action" value="add">
                                <div class="col-lg-12 ">
                                    <div class="form-group">
                                        <label>Clave Actual</label>
                                         <input type="text" name="clave_actual"
                                                required class="cloaked form-control"
                                                id="id_clave_actual"
                                                placeholder="********">

                                    </div>
                                </div>
                                <div class="col-lg-12 ">
                                    <div class="form-group">
                                        <label>Clave Nueva</label>
                                        <input  type="text" name="clave"
                                                class="cloaked form-control"
                                                id="id_clave" placeholder="********" required>
                                    </div>
                                </div>
                                <!--BOTON-->
                                <div class="col-lg-12">
                                    <div class="send-btn">
                                        <button onclick="window.location = '/'" class="btn btn-danger" type="button">
                                            Cancelar
                                        </button>
                                        <button type="submit" class="btn btn-success">Guardar</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="/static/sweetalert2/dist/sweetalert2.all.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <link href="/static/selectmultiple/select2.min.css" rel="stylesheet">
    <script src="/static/selectmultiple/select2.min.js"></script>
    <link rel="stylesheet" href="/static/dropify/css/dropify.min.css">
    <script src="/static/dropify/js/dropify.min.js"></script>
    <script src="/static/validaciones/funciones.js"></script>
    <script type="text/javascript" src="/static/input-cloak/jquery-inputcloak.min.js"></script>
{% endblock %}

{% block jscript %}
    <script>

        $(function () {
            $('#id_clave').on('blur', function () {
                var clave = $('#id_clave').val();
                if (clave.length < 8) {
                    swal("CLAVE DEBE CONTENER MINIMO 8 CARACTERES");
                }

            });
        });

        window.onload = function () {
            {% if messages %}
                {% for message in messages %}
                    Swal.fire('{{ message }}','ALERTA','warning');
                {% endfor %}
            {% endif %}
        }

        $(document).ready(function () {
            $('.cloaked').inputCloak();
        });
    </script>
{% endblock %}

templates/sitio/perfil.html
{% extends 'sitio/base.html' %}

{% block main %}

    <div class="page-header" style="background: url(/static/sitio/assets/img/banner1.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumb-wrapper">
                        <h2 class="page-title">Perfil</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-12 col-lg-4 page-sidebar">
                    <aside>
                        <div class="sidebar-box">
                            <div class="user">
                                <div class="usercontent">
                                    <h3>{{ request.user.first_name }} {{ request.user.last_name }}</h3>
                                    <h4>{{ request.user.email }}</h4>
                                </div>
                            </div>
                            <nav class="navdashboard">
                                <ul>
                                    <li>
                                        <a class="active" href="/perfil/">
                                            <i class="fas fa-user"></i>
                                            <span>Editar Información</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="/clave/">
                                            <i class="fas fa-user-lock"></i>
                                            <span>Cambiar Clave</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="/localesusuarios/">
                                            <i class="fas fa-credit-card"></i>
                                            <span>Ver Locales</span>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </aside>
                </div>
                <div class="col-lg-8 col-md-12 col-xs-12 page-content">
                    <div class="inner-box">
                        <div class="welcome-msg">
                            <div class="user-content">
                                <p class="small">La última vez que iniciaste sesión fue: {{ request.user.last_login }}</p>
                            </div>
                        </div>
                        <form enctype="multipart/form-data" id="frmEntidad" method="POST"
                          action="{{ ruta }}" data-parsley-validate
                          class="form-horizontal form-label-left">{% csrf_token %}
                            <div class="row">

                                <input type="hidden" name="id" value="{{ request.user.pk }}">
                                <input type="hidden" name="action" value="edit">
                                <div class="col-lg-12 ">
                                    <div class="form-group">
                                        <label>Foto</label>
                                        <input type="file" id="dropify-event" id="id_foto" name="foto"
                                       data-default-file="/media/{{ request.user.usuarios.foto }}"
                                       data-allowed-file-extensions="jpg png">
                                    </div>
                                </div>
                                <div class="col-lg-12 ">
                                    <div class="form-group">
                                        <label>Username</label>
                                        <input type="text" name="username" id="id_username" class="form-control" value="{{ request.user.username }}"
                                               onKeyPress="return soloValidacion(event)">
                                    </div>
                                </div>
                                <div class="col-lg-12 ">
                                    <div class="form-group">
                                        <label>Nombres</label>
                                        <input type="text" name="first_name" id="id_first_name"
                                               class="form-control" value="{{ request.user.first_name }}"
                                               onKeyPress="return sololetras(event)">
                                    </div>
                                </div>
                                <div class="col-lg-12 ">
                                    <div class="form-group">
                                        <label>Apellidos</label>
                                        <input type="text" name="last_name" id="id_last_name"
                                               class="form-control" value="{{ request.user.last_name }}"
                                               onKeyPress="return sololetras(event)">
                                    </div>
                                </div>
                                <div class="col-lg-12 ">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="email" name="email" id="id_email" class="form-control" value="{{ request.user.email }}">
                                    </div>
                                </div>
                                <div class="col-lg-12 ">
                                    <div class="form-group">
                                        <label>Documento</label>
                                        <input type="text" name="documento" id="id_documento" onKeyPress="return soloNumeros(event)"
                                               class="form-control" value="{{ request.user.usuarios.documento }}">
                                    </div>
                                </div>
                                <div class="col-lg-12 ">
                                    <div class="form-group">
                                        <label>Telefono</label>
                                        <input type="text" maxlength="10" name="telefono" id="id_telefono" onKeyPress="return soloNumeros(event)"
                                               class="form-control" value="{{ request.user.usuarios.telefono }}">
                                    </div>
                                </div>
                                <div class="col-lg-12 ">
                                    <div class="form-group">
                                        <label>Celular</label>
                                        <input type="text" maxlength="10" name="celular" id="id_celular" onKeyPress="return soloNumeros(event)"
                                               class="form-control" value="{{ request.user.usuarios.celular }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Dirección</label>
                                        <textarea class="form-control"
                                                  rows="5" name="direccion">{{ request.user.usuarios.direccion }}</textarea>
                                    </div>
                                </div>
                                <!--BOTON-->
                                <div class="col-lg-12">
                                    <div class="send-btn">
                                        <button onclick="window.location = '/'" class="btn btn-danger" type="button">
                                            Cancelar
                                        </button>
                                        <button type="submit" class="btn btn-success">Guardar</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="/static/sweetalert2/dist/sweetalert2.all.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <link href="/static/selectmultiple/select2.min.css" rel="stylesheet">
    <script src="/static/selectmultiple/select2.min.js"></script>
    <link rel="stylesheet" href="/static/dropify/css/dropify.min.css">
    <script src="/static/dropify/js/dropify.min.js"></script>
    <script src="/static/validaciones/funciones.js"></script>
    <script type="text/javascript" src="/static/input-cloak/jquery-inputcloak.min.js"></script>
{% endblock %}

{% block jscript %}
    <script>
        $(document).ready(function () {
            $('.js-example-basic-multiple').select2();
            $('.js-example-basic-single').select2();
            $('.cloaked').inputCloak();
    });

        $(function () {
            $('.dropify').dropify();
            var drEvent = $('#dropify-event').dropify();
            drEvent.on('dropify.afterClear', function (event, element) {
                Swal.fire({
                    toast: true,
                    position: 'top-end',
                    type: 'success',
                    title: 'Foto eliminada con exito.',
                    showConfirmButton: false,
                    timer: 3500
                })
            });
            var drEvent1 = $('#dropify-event-cv').dropify();
            drEvent1.on('dropify.afterClear', function (event, element) {
                Swal.fire({
                    toast: true,
                    position: 'top-end',
                    type: 'success',
                    title: 'Archivo eliminado con exito.',
                    showConfirmButton: false,
                    timer: 3500
                })
            });
        });

        $(function () {
            $('#id_username').on('blur', function () {
                var username = $("#id_username").val();
                if (username == '') {
                    Swal.fire('Nombre de usuario no valido','Perfil','error')
                } else {
                    $.ajax({
                        data: {'action': 'duplicado-perfil', 'username': username},
                        url: '/perfil/',
                        type: 'post',
                        success: function (data) {
                            var object = JSON.parse(data)
                            if (object.username == 'Existe') {
                                $("#id_username").val("");
                                Swal.fire('Usuario ya existe','Perfil','error')
                            }
                        }
                    });
                }

            });
        });

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie != '') {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                            var cookie = jQuery.trim(cookies[i]);
                            // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }

                if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                    // Only send the token to relative URLs i.e. locally.
                    xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                }
            }
        });

        window.onload = function () {
            {% if messages %}
                {% for message in messages %}
                    Swal.fire('{{ message }}');
                {% endfor %}
            {% endif %}
         }
    </script>
{% endblock %}