multirestaurante/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.views.static import serve
from django.urls import include, path
from multirestaurante.settings import STATIC_ROOT, MEDIA_ROOT
from seguridad.views import auditoria
from sitio.views import *
from seguridad.index import *
from sitio.perfil import *
from seguridad.clave import *
from sitio.registro import *
from sitio.locale import *
from sitio.local import *
from sitio.faq import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',sitio,name='sitio'),
    path('panel/', index,  name='index'),
    path('seguridad/',include('seguridad.urls')),
    path('restaurante/', include('restaurante.urls')),
    path('auditoria/', auditoria),
    path('perfil/', perfil),
    path('localesusuarios/', locales),
    path('locales/', local),
    path('faq/', faq),
    path('clave/', clave),
    path('registro/', registro),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})
]

admin.site.site_header = 'ADMINISTRACION MULTIRESTAURANTE'
WKHTMLTOPDF_CMD_OPTIONS = {'encoding': 'utf8', 'quiet': True}

seguridad/urls.py
from django.conf.urls import url
from seguridad.login import login_session,logout_user
from seguridad.recuperar_clave import recuperar
from seguridad.clave import clave
from seguridad.usuarios import *

urlpatterns = [
    url(r'^login/', login_session),
    url(r'^logout/', logout_user),
    url(r'^recuperar/', recuperar),
    url(r'^usuarios/$', usuarios),
    url(r'^clave/$', clave),
]

seguridad/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.template.defaulttags import now

class Modulo(models.Model):
    url = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    icono = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=100)
    activo = models.BooleanField(default=True)
    orden = models.IntegerField(default=0)

    def __str__(self):
        return '{} ({})'.format(self.nombre, self.url)

    class Meta:
        verbose_name = 'Módulo'
        verbose_name_plural = 'Módulos'
        ordering = ['orden']

class ModuloGrupo(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=200, blank=True)
    icono = models.CharField(max_length=100)
    modulos = models.ManyToManyField(Modulo)
    grupos = models.ManyToManyField(Group)
    prioridad = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return '{} {}'.format(self.nombre, self.prioridad)

    class Meta:
        verbose_name = 'Grupo de Módulos'
        verbose_name_plural = 'Grupos de Módulos'
        ordering = ('prioridad', 'nombre')

    def modulos_activos(self):
        return self.modulos.filter(activo=True).order_by('nombre')

class AudiUsuarioTabla(models.Model):
    TIPOS_ACCIONES = (
        ('A', 'A'),   # Adicion
        ('M', 'M'),   # Modificacion
        ('E', 'E')    # Eliminacion
    )
    usuario = models.ForeignKey(User,on_delete=models.PROTECT, verbose_name='Usuario')
    tabla = models.CharField(max_length=100, verbose_name='Tabla')
    registroid = models.IntegerField(verbose_name='Registro Id')
    registroname = models.CharField(max_length=100,verbose_name='Registro Name')
    accion = models.CharField(choices=TIPOS_ACCIONES, max_length=10, verbose_name='Accion')
    fecha = models.DateField(verbose_name='Fecha')
    hora = models.TimeField(verbose_name='Hora')
    estacion = models.CharField(max_length=100, verbose_name='Estacion')

    def save(self, force_insert=False, force_update=False, using=None, **kwargs):
        self.registroname = self.registroname.upper()
        super(AudiUsuarioTabla, self).save(force_insert, force_update, using)


    def __str__(self):
        return "{} - {} [{}]".format(self.usuario.username, self.tabla, self.accion)

    class Meta:
        verbose_name = 'Auditoria Usuario '
        verbose_name_plural = 'Auditorias Usuarios'
        ordering = ('-fecha', 'hora')

class Correo(models.Model):
    correo = models.CharField(max_length=100)
    clave = models.CharField(max_length=100)

templates/categoria/frm_categoria.html
{% extends 'base.html' %}
{% block headcss %}

{% endblock %}
{% block header %}
    {% include 'header.html' %}
{% endblock %}
{% block main %}

    <div class="row-fluid">
        <div class="span12">
            <ul class="breadcrumb">
                <li><a href="/panel/">Inicio</a><span class="divider"></span></li>
                <li><a href="{{ ruta }}" class="active">{{ model }}</a> <span class="divider">/</span></li>
            </ul>
        </div>
    </div>
    <!-- Formulario de Mantenimiento-->
    <div class=container>

        <div class='row-fluid'>
            <div class='col-md-14'>
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        <h4><strong>{{ titulo }}</strong></h4>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" enctype="multipart/form-data" id="frmEntidad" method="POST"
                              action="{{ ruta }}">{% csrf_token %}
                            <input type="hidden" name="id" value="{{ id }}">
                            <input type="hidden" name="action" value="{{ action }}">
                            <!-- Campos del formulario-->



                            <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                           for="last-name">Descripcion<span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input class="form-control" placeholder="Descripcion"
                                                                               id="id_descripcion"  {% if accion == 'ver' %}
                                                                               disabled {% endif %}
                                                                               value="{{ descripcion }}"
                                                                               maxlength="50" name="descripcion" type="text"
                                                                               {% if action == 'add' %}required{% endif %}/>
                                    </div>
                                </div>

                            <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">¿Activo?
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input
                                                {% if accion == 'ver' %}
                                                    disabled {% endif %}
                                                    type="checkbox" id="estado" name="estado"
                                                    class="js-switch"
                                                {% if estado == True %} checked  {% endif %}/>
                                    </div>
                                </div>


                            <div class="well well-sm">
                                <div class="row">
                                    <div class="col-xs-5 col-lg-offset-4">
                                        <div class="btn btn-group col-md-offset-3 ">

                                            <button type="submit" style="border-radius: 0px" {% if accion == 'ver' %}
                                                                               disabled {% endif %}
                                                    class="btn btn-success sbox" id="add">
                                                <i class="glyphicon glyphicon-save"></i> Guardar
                                            </button>

                                            <button type="button"
                                                    onclick="window.location = '{{ ruta }}'"
                                                    style="border-radius: 0px" class="btn btn-danger sbox"
                                                    id="add1">
                                                <i class="glyphicon glyphicon-remove"></i> Cancelar
                                            </button>
                                        </div>
                                    </div>


                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script src="/static/validaciones/funciones.js"></script>
    <link href="/static/selectmultiple/select2.min.css" rel="stylesheet">
    <script src="/static/selectmultiple/select2.min.js"></script>
    <script type="text/javascript" src="/static/input-cloak/jquery-inputcloak.min.js"></script>
{% endblock %}

{% block jscript %}
    <script>

        $(document).ready(function () {
            $('.cloaked').inputCloak();
        });





        $(document).ready(function () {
            $('.js-example-basic-single').select2();
        });

    </script>
{% endblock %}

templates/categoria/listar_categoria.html
{% extends 'base.html' %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block main %}
    <div class="row-fluid">
        <div class="span12">
            <ul class="breadcrumb">
                <li><a href="/panel/">Inicio</a><span class="divider"></span></li>
                <li><a href="{{ ruta }}" class="active">{{ model }}</a> <span class="divider">/</span></li>
            </ul>
        </div>
    </div>

    <div class="panel panel-footer">
        <div class="panel-heading">
            <div class="row-fluid">
                <h2>Listado de {{ model }}</h2>

                 {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-danger alert-dismissible fade in" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">×</span>
                            </button>
                            <strong>Alerta! </strong> {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}

                <div class="container-fluid well-sm" style="padding-top: 3%">
                    <div class="col-lg-1">
                        <a style="border-radius: 0px" href="#" rel="action" data-json='{"action": "add","id":""}'
                           class="btn btn-success sbox">
                            <i class="glyphicon glyphicon-plus-sign"></i>
                            Nuevo Registros
                        </a>
                    </div><br>

                    <form class="col-lg-offset-4" method="GET" action="{{ ruta }}">
                        <div class="input-group">
                            <div class="input-group-btn">

                                <button type="button" class="btn btn-info">Buscar</button>

                            </div>

                            <input type="text" name="criterio" value="{{ criterio }}" class="form-control"
                                   placeholder="Ponga una descripción válida..">

                            <div class="input-group-btn">
                                <button class="btn btn-primary"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>

        <!-- Tabla -->

        <div class="panel-body">
            <div class="panel panel-default">
                <table id="tb_marca"
                   class="table table-hover table-striped table-condensed" width="100%">
                    <thead style="background: #2c4c69; color:#ffffff">
                        <tr class="headings">
                            <th class="column-title">Id</th>
                            <th class="column-title">Nombres</th>
                            <th class="column-title">Estado</th>
                            <th class="column-title">Acción</th>
                        </tr>
                        </thead>
                    <tbody>
                        {% for c in categoria %}
                            <tr>
                                <td>{{ c.id }}</td>
                                <td>{{ c.descripcion }}</td>
                                <td><center>
                                    {% if c.estado == True %}
                                        <p><span class="label label-success">ACTIVO</span></p>
                                    {% else %}
                                        <p><span class="label label-danger">INACTIVO</span></p>
                                    {% endif %}</center>
                                </td>

                                <td>
                                <div class="btn-group">
                                    <a href="#" rel="action" class="btn btn-default btn-sm"
                                       data-toggle="tooltip"
                                       data-placement="bottom"
                                       title="Ver"
                                       data-json='{"action":"ver","id":"{{ c.id }}","nombre":"{{ c.descripcion }}"}'><i
                                            class="glyphicon glyphicon-eye-open"></i></a>   </div>

                                <div class="btn-group">
                                        <a href="#" rel="action" class="btn btn-info btn-sm"
                                       data-toggle="tooltip"
                                       data-placement="bottom"
                                       title="Editar"
                                           data-json='{"action":"edit","id":"{{ c.id }}","nombre":"{{ c.descripcion}}"}'><i
                                                class="glyphicon glyphicon-edit"></i></a>   </div>
                                <div class="btn-group">
                                        <a href="#" rel="action" class="btn btn-warning btn-sm"
                                       data-toggle="tooltip"
                                       data-placement="bottom"
                                       title="Desactivar" data-json='{"action":"elim","id":"{{ c.id }}","nombre":"{{ c.descripcion }}"}'><i
                                                class="glyphicon glyphicon-remove"></i></a>   </div>

                                </td>


                            </tr>
                        {% endfor %}
                        </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- inicio formulario Modal para Eliminar -->
     <div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">

                <form name="frmEliminar" id="frmEliminar" method="POST" action="{{ ruta }}"> {% csrf_token %}
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">¿Desea eliminar este registro?</h4>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="id" id="id" value="">
                        <input type="hidden" name="action" value="elim">

                        <label>Codigo:</label>
                        <span id="codigo"></span><br><br>
                        <label>Nombre:</label>
                        <span id="nombre"></span>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-danger" id="btnElimiar">Eliminar</button>
                    </div>
                </form>

            </div>
        </div>
    </div>

{% endblock %}

{% block jscript %}
    <script>

        $(function () {
            $('#contenedor').on('click', 'a[rel="action"]', function () {
                var data = $(this).data('json'),
                        action = data.action,
                        nombre = data.nombre,
                        id = data.id;
                logo = data.logo;

                if (action == 'elim') {
                    Swal.fire({
                        title: 'SEGURO QUE DESEA ELIMINAR ESTE REGISTRO?',
                        text: "No podrás revertir esto!",
                        type: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Yes'
                    }).then((result) => {
                        if(result.value)
                    {
                        $.ajax({
                            data: {'id': id,'action':action},
                            url: '{{ ruta }}',
                            type: 'get',
                            success: function (data) {
                                console.log(data)
                                var object = JSON.parse(data)
                                console.log(object.id)
                                if (object.id == 'Existe') {
                                    Swal.fire(
                                            'Eliminado!',
                                            'Registro eliminado.',
                                            'success'
                                    )
                                    setTimeout('window.location.reload()', 1500);
                                } else {
                                    alertify.error('No se pudo eliminar este registro');
                                }
                            }
                        });
                    }
                })
                    return;
                }

                window.location = '{{ ruta }}?action=' + action + '&id=' + id;
            });
        });


    </script>
{% endblock %}

</body>
</html>